FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443
EXPOSE 8080

ENV ASPNETCORE_HTTP_PORTS=80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
WORKDIR /src
RUN dotnet restore "src/BidCalculationService.Api/BidCalculationService.Api.csproj"
RUN dotnet build "src/BidCalculationService.Api/BidCalculationService.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "src/BidCalculationService.Api/BidCalculationService.Api.csproj" -c Release -o /app/publish 

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "BidCalculationService.Api.dll"]